### ISSUE TITLE
Question: how to pass class member as a callback?

### ISSUE THREAD

**Issue by quarcko** [embeddedmz/ftpclient-cpp#27]
Sorry to bug you again, but i'm no expert in c++ templates, and can't wrap my head around
how to pass a class member method to:
ftp->SetProgressFnCallback(this, **&Class::method**);

it gives:
no known conversion for argument 2 from ‘int (MainWindow::*)(void*, double, double, double, double)’ to ‘const ProgressFnCallback& {aka const std::function<int(void*, double, double, double, double)>&}’

**Comment by quarcko** [comment]
So, for anybody else interested in similar things, here is the solution, although i did not find
how to pass Class method directly, but here is workaround:

Firstly, you have to create a callback function, like is needed, and make it "friend" of your class you want to access.
then when calling SetProgressFnCallback pass 'this' or pointer to your class instance:
ftp->SetProgressFnCallback(this, &extProgCallback);

and here is callback function with access to class private variables and etc... :

int extProgCallback(void *ptr, double dTotalToDownload, double dNowDownloaded, double dTotalToUpload, double dNowUploaded)
{
    qDebug() << "Upload progress: " << dNowUploaded << "/" << dTotalToUpload;

    if(ptr)
    {
        embeddedmz::CFTPClient::ProgressFnStruct *prFnStruct = static_cast<embeddedmz::CFTPClient::ProgressFnStruct*>(ptr);
        if(prFnStruct && prFnStruct->pOwner)
        {
            MainWindow *thisWin = static_cast<MainWindow*>(prFnStruct->pOwner);
            if(thisWin)
            {
                thisWin->progDiag->setRange(0, dTotalToUpload); //Access private progDiag
                thisWin->progDiag->setValue(dNowUploaded);
            }
        }
    }

    QApplication::processEvents( QEventLoop::AllEvents, 100 );
    return 0;
}

**Comment by embeddedmz** [comment]
@quarcko In C++, object methods (not static), there's a hidden parameter in the arguments list and it's the "this" parameter. So if you need to pass a function pointer to a C API, you need to use class methods (ie static methods that doesn't require un object to be created). To keep your stuff encapsulated, use the static keyword instead of using a normal function.

std::function is just another way to declare a pointer to a function and you can use to store both classic function pointers and object methods (http://www.cplusplus.com/reference/functional/function/function/).

IIRC, in C++, normal functions (or static methods) and object methods of classes not using a virtual table (polymorphism with the keyword virtual) pointers contains an address to the code in the text segment of a program (e.g. 0xABCD015) as the compiler can statically determine the code that will be executed.

However, object methods where the keyword virtual is used, are just offsets (0, 1, 2 etc...) and the segment that contains methods begins from the pointer to the virtual table which is hidden in object members (dynamic dispatch as the compiler can't determine what objects will created and thus cannot determine the method to be executed ie the base class method or the overriden subclass method - google virtual table, it's an interesting subject, if you need to do OOP with C, you will have to do the same thing a C++ compiler does ;) ).

**Comment by quarcko** [comment]
@embeddedmz 

I tried to change from 'friend function' to 'static method' and yes - everything works perfectly and looks a lot nicer :)
Thanks for the tip!

More advanced reading i will leave for later, it's Friday already! :)
Thanks again!

**Comment by quarcko** [comment]
Thanks for great info again, yeah i know Qt stuff waaay better than C++ standarts :rofl: 
My app uses alot of Multithreading and Event loop stuff as well,
I just did not thought or checked that curl can be running in another thread.. but you know your code better, so will 
use invokeMethod for sure! 

Have a great weekend too!
